/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2021-10-05

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */


#include <command.h>
#include <uart.h>
#include <lcd_control.h>
#include "stm32f4xx.h"
#include <macros_utiles.h>
#include <timer_control.h>


/* Private macro */
/* Private variables */
uint8_t buffer[20];
int ptr_write = 0;
int ptr_read = 0;
int bytesToRead = 0;
int position = 0;

//extern timerValue;
unsigned int currentTime = 0;
unsigned int interruptCount = 0;
extern unsigned int waitCount;
extern unsigned int monitoringOn;

/* Private function prototypes */
/* Private functions */
void TIM3_IRQHandler(void)
{
	TIM3->SR &= ~BIT0; // update interupt flag to 0
	if (monitoringOn){GPIOD->ODR &= ~BIT12;
//	  GPIOD->ODR &= ~BIT13;
	  GPIOD->ODR |= BIT14;}
	interruptCount++;
	BoucleDAttente(2000);
}

void TIM2_IRQHandler(void)
{
	TIM2->SR &= ~BIT0; // update interrupt flag to 0
	waitCount = 1;
}

void UART4_IRQHandler(void){
	uint8_t data = UART4->DR;
	if(monitoringOn){GPIOD->ODR &= ~BIT12;
	  GPIOD->ODR ^= BIT13;
	  GPIOD->ODR &= ~BIT14;}
	buffer[ptr_write] = data;
	ptr_write++;
	if(ptr_write>=20) ptr_write = 0;
	bytesToRead++;
}


/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
  int i = 0;

  /**
  *  IMPORTANT NOTE!
  *  The symbol VECT_TAB_SRAM needs to be defined when building the project
  *  if code has been located to RAM and interrupts are used. 
  *  Otherwise the interrupt table located in flash will be used.
  *  See also the <system_*.c> file and how the SystemInit() function updates 
  *  SCB->VTOR register.  
  *  E.g.  SCB->VTOR = 0x20000000;  
  */

  /* TODO - Add your application code here */


  configureUART();
  configureLcdGPIO();
  configureLCD();
  setupMonitoring();
  // config Led
   RCC->AHB1ENR |= BIT3;
   GPIOD->MODER |= BIT30; // set mode de input output
   GPIOD->MODER &= ~BIT31;
  configureTIM3(1000);
//  configureTIM2(1000000);





  /* Infinite loop */
  while (1)
  {
	  i++;
	  if(monitoringOn)
	  {
		  GPIOD->ODR |= BIT12;
//		  GPIOD->ODR &= ~BIT13;
		  GPIOD->ODR &= ~BIT14;
	  }

	  if(interruptCount >= COUNTCOMPARE)
	  {
		  interruptCount = 0;
		  writeTime(currentTime++);
	  }
	  if (bytesToRead >= 3)
		  readCommand(buffer);

	  if(monitoringOn)
	  {
		  GPIOD->ODR &= ~BIT12;
	  }

  }
}
