/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2021-10-05

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "macros_utiles.h"
#include "memory_control.h"
#include "lcd_control.h"

/* Private macro */
#define TAILLE 67
uint8_t buffer[20];
int indx = 0;
extern timerValue;
unsigned int currentTime = 0;

/* Private variables */
/* Private function prototypes */
/* Private functions */



/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
  int i = 0;

  /**
  *  IMPORTANT NOTE!
  *  The symbol VECT_TAB_SRAM needs to be defined when building the project
  *  if code has been located to RAM and interrupts are used. 
  *  Otherwise the interrupt table located in flash will be used.
  *  See also the <system_*.c> file and how the SystemInit() function updates 
  *  SCB->VTOR register.  
  *  E.g.  SCB->VTOR = 0x20000000;  
  */

  /* TODO - Add your application code here */


  configureUART();
  configureLcdGPIO();
  configureLCD();

//  unsigned char p_mots[TAILLE];
//  unsigned char p_erase[TAILLE];
//  unsigned char p_recv[TAILLE];
//  unsigned char p_recv2[TAILLE];
//  unsigned char p_recv3[TAILLE];
//
//  for(int iter = 0; iter < TAILLE; iter++)
//  {
//	  p_mots[iter] = 'i' + iter;
//	  p_erase[iter] = 0xff;
//	  p_recv[iter] = 0;
//	  p_recv2[iter] =  0;
//	  p_recv3[iter] =  0;
//  }



  /* Infinite loop */
  while (1)
  {
	i++;

  if(currentTime != timerValue)
  {
    currentTime = timerValue;
    writeTime(currentTime);
  }

	int data = receiveByteUART();
	buffer[indx] = data;
	indx++;
	if (indx>=30) indx = 0;

  }
}
